MEMES = {
    'AAAAAND_ITS_GONE': {
        'id': 766986,
        'text0': None,
        'text1': "Aaaaand it's gone",
        'text_location': 'text0',
    },
    'AM_I_THE_ONLY_ONE_AROUND_HERE': {
        'id': 259680,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'ANCIENT_ALIENS': {
        'id': 101470,
        'text0': None,
        'text1': "Therefore aliens",
        'text_location': 'text0',
    },
    'BAD_LUCK_BRIAN': {
        'id': 61585,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'BART_HITTING_HOMER_WITH_A_CHAIR': {
        'id': 137353308,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'BATMAN_SLAPPING_ROBIN': {
        'id': 438680,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'BERNIE_MITTENS': {
        'id': 293514871,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'BERNIE_ONCE_AGAIN_ASKING_FOR_SUPPORT': {
        'id': 222403160,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'BIKE_FALL': {
        'id': 79132341,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'BIRD_BOX': {
        'id': 164335977,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'BORIS_JOHNSON': {
        'id': 86808920,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'BORIS_JOHNSON_CONFUSED': {
        'id': 263558311,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'BORIS_JOHNSON_LAURA_BENCH': {
        'id': 200544291,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'BORIS_JOHNSON_SPEECH': {
        'id': 250805008,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'BRACE_YOURSELVES_X_IS_COMING': {
        'id': 61546,
        'text0': "Brace yourselves",
        'text1': None,
        'text_location': 'text1',
    },
    'BUDDY_CHRIST': {
        'id': 17699,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'BUT_THATS_NONE_OF_MY_BUSINESS':{
        'id': 16464531,
        'text0': None,
        'text1': "But that's none of my business",
        'text_location': 'text0',
    },
    'CAPTAIN_PICARD_FACEPALM': {
        'id': 1509839,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'CHANGE_MY_MIND': {
        'id': 129242436,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'CREEPY_CONDESCENDING_WONKA': {
        'id': 61582,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'DEAN_GALLAGHER': {
        'id': 296610665,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'DISASTER_GIRL': {
        'id': 97984,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'DR_EVIL_LASER': {
        'id': 40945639,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'ELON_SMOKING_A_JOINT': {
        'id': 150194498,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'EVIL_TODDLER': {
        'id': 235589,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'FINDING_NEVERLAND': {
        'id': 6235864,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'FIRST_WORLD_PROBLEMS': {
        'id': 61539,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'FLEXIBLE_LAPTOP_GUY': {
        'id': 79627729,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'FRY_MEGAPHONE': {
        'id': 94139831,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'FUTURAMA_FRY': {
        'id': 61520,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'GRANDMA_FINDS_THE_INTERNET': {
        'id': 61556,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'GRUMPY_CAT': {
        'id': 405658,
        'text0': None,
        'text1': "No",
        'text_location': 'text0',
    },
    'GUY_HOLDING_CARDBOARD_SIGN': {
        'id': 216951317,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'HEDONISMBOT': {
        'id': 694765,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'HIDE_THE_PAIN_HAROLD': {
        'id': 27813981,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'ILL_JUST_WAIT_HERE': {
        'id': 109765,
        'text0': None,
        'text1': "I'll just wait here",
        'text_location': 'text0',
    },
    'IS_THIS_A_PIGEON': {
        'id': 100777631,
        'text0': "Is this",
        'text1': None,
        'text_location': 'text1',
    },
    'JACK_SPARROW_BEING_CHASED': {
        'id': 460541,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'KEVIN_HART': {
        'id': 7253945,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'LINUS_FU': {
        'id': 101386778,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'MARKED_SAFE_FROM': {
        'id': 161865971,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'MARVEL_CIVIL_WAR_1': {
        'id': 28034788,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'MEL_GIBSON_JESUS': {
        'id': 116570292,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'MUGATU_SO_HOT_RIGHT_NOW': {
        'id': 21604248,
        'text0': None,
        'text1': "So hot right now",
        'text_location': 'text0',
    },
    'PETER_PARKER_CRY': {
        'id': 53764,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'PHILOSORAPTOR': {
        'id': 61516,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'PICARD_MAKE_IT_SO': {
        'id': 9253958,
        'text0': None,
        'text1': "Make it so",
        'text_location': 'text0',
    },
    'PICARD_WTF': {
        'id': 245898,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'PRESIDENTIAL_ALERT': {
        'id': 157978092,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'SAY_THAT_AGAIN_I_DARE_YOU': {
        'id': 124212,
        'text0': None,
        'text1': "Say that again I dare you",
        'text_location': 'text0',
    },
    'SCARED_CAT': {
        'id': 4173692,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'SEE_NOBODY_CARES': {
        'id': 6531067,
        'text0': None,
        'text1': "See! Nobody cares",
        'text_location': 'text0',
    },
    'SHUT_UP_AND_TAKE_MY_MONEY_FRY':{
        'id': 176908,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'SPARTA_LEONIDAS': {
        'id': 195389,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'SPONGEBOB_IGHT_IMMA_HEAD_OUT': {
        'id': 196652226,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'STAR_WARS_NO': {
        'id': 19194965,
        'text0': None,
        'text1': "Noooooooo",
        'text_location': 'text0',
    },
    'STAR_WARS_YODA': {
        'id': 14371066,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'SUCCESS_KID': {
        'id': 61544,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'SURPRISED_KOALA': {
        'id': 27920,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'TEN_GUY': {
        'id': 101440,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'THAT_WOULD_BE_GREAT': {
        'id': 563423,
        'text0': None,
        'text1': "That would be great",
        'text_location': 'text0',
    },
    'THE_MOST_INTERESTING_MAN_IN_THE_WORLD': {
        'id': 61532,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'THE_SCROLL_OF_TRUTH': {
        'id': 123999232,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'THINKING_ABOUT_OTHER_WOMEN': {
        'id': 110163934,
        'text0': "I bet he's thinking about other women",
        'text1': None,
        'text_location': 'text1',
    },
    'THIS_IS_FINE': {
        'id': 55311130,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'TRUMP_BILL_SIGNING': {
        'id': 91545132,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'TRUMP_LAWN_MOWER': {
        'id': 114117745,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'WAITING_SKELETON': {
        'id': 4087833,
        'text0': None,
        'text1': "I'll just wait here",
        'text_location': 'text0',
    },
    'WELL_YES_BUT_ACTUALLY_NO': {
        'id': 170715647,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'WOMAN_YELLING_AT_A_CAT': {
        'id': 188390779,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'X_ALL_THE_Y': {
        'id': 61533,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'YO_DAWG_HEARD_YOU_LIKE': {
        'id': 101716,
        'text0': None,
        'text1': None,
        'text_location': 'text1',
    },
    'Y_U_NO': {
        'id': 61527,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
    'Y_THO': {
        'id': 59204652,
        'text0': None,
        'text1': "Y THO",
        'text_location': 'text0',
    },
    'ZOIDBERG': {
        'id': 61573,
        'text0': None,
        'text1': None,
        'text_location': 'text0',
    },
}
